{% set version = "0.6.19" %}

package:
  name: aws-c-auth
  version: {{ version }}

source:
  url: https://github.com/awslabs/aws-c-auth/archive/v{{ version }}.tar.gz
  sha256: 2b6b05e046227f87c39d0dd821759273c80e864689dfb36bbc64bed86dc8336f
  patches:                                # [linux64 or (linux and aarch64)]
    - 0001-skip-test-failing-on-CI.patch  # [linux64 or (linux and aarch64)]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-auth", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - ninja-base
    - patch  # [linux64 or (linux and aarch64)]
  host:
    - aws-c-cal 0.5.20
    - aws-c-common 0.8.5
    - aws-c-http 0.6.25
    - aws-c-io 0.13.10
    - aws-c-sdkutils 0.1.6

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-auth${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/auth/auth.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\auth\\auth.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-auth.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-auth
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'C99 library implementation of AWS client-side authentication: standard credentials providers and signing.'
  description: |
    C99 library implementation of AWS client-side authentication: standard credentials providers and signing.
    From a cryptographic perspective, only functions with the suffix "_constant_time" should be considered constant time.
  dev_url: https://github.com/awslabs/aws-c-auth
  doc_url: https://github.com/awslabs/aws-c-auth
extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
