{% set name = "aws-c-auth" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 12a29eb62c61cef4b38c90d4f0dd2657dc585a15c138d60941d6f20c1ad3b12d

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-auth", max_pin="x.x.x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cmake >=3.9
    - ninja-base
  host:
    - aws-c-cal 1.0.0
    - aws-c-common 1.0.1
    - aws-c-http 1.0.0
    - aws-c-io 1.0.0
    - aws-c-sdkutils 1.0.0

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-auth${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/auth/auth.h  # [unix]
    - if not exist %LIBRARY_INC%\aws\auth\auth.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\aws-c-auth.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-auth
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'C99 library implementation of AWS client-side authentication: standard credentials providers and signing.'
  description: |
    C99 library implementation of AWS client-side authentication: standard credentials providers and signing.
    From a cryptographic perspective, only functions with the suffix "_constant_time" should be considered constant time.
  doc_url: https://github.com/awslabs/aws-c-auth
  dev_url: https://github.com/awslabs/aws-c-auth
extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp