{% set version = "0.8.5" %}

package:
  name: aws-c-auth
  version: {{ version }}

source:
  url: https://github.com/awslabs/aws-c-auth/archive/v{{ version }}.tar.gz
  sha256: 302f40c189456defe14860d13a22a6bf435cdb9eee2b60c585e8725825385cbb

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-auth", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - ninja
  host:
    - aws-c-cal 0.8.5
    - aws-c-common 0.11.1
    - aws-c-http 0.9.3
    - aws-c-io 0.17.0
    - aws-c-sdkutils 0.2.3

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-auth${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/auth/auth.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\auth\\auth.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-auth.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-auth
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'C99 library implementation of AWS client-side authentication: standard credentials providers and signing.'
  description: |
    C99 library implementation of AWS client-side authentication: standard credentials providers and signing.
    From a cryptographic perspective, only functions with the suffix "_constant_time" should be considered constant time.
  doc_url: https://github.com/awslabs/aws-c-auth
  dev_url: https://github.com/awslabs/aws-c-auth
extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp