{% set name = "aws-c-auth" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 704b2f965c31d9d0fd8d9ab207bc8c838e3683c56bd8407e472bbc8fa9f9a209

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-auth", max_pin="x.x.x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cmake >=3.9
    - ninja-base
  host:
    - aws-c-cal 0.9.13
    - aws-c-common 0.12.6
    - aws-c-http 0.10.7
    - aws-c-io 0.23.3
    - aws-c-sdkutils 0.2.4

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-auth${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/auth/auth.h  # [unix]
    - if not exist %LIBRARY_INC%\aws\auth\auth.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\aws-c-auth.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-auth
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'C99 library implementation of AWS client-side authentication: standard credentials providers and signing.'
  description: |
    C99 library implementation of AWS client-side authentication: standard credentials providers and signing.
    From a cryptographic perspective, only functions with the suffix "_constant_time" should be considered constant time.
  doc_url: https://github.com/awslabs/aws-c-auth
  dev_url: https://github.com/awslabs/aws-c-auth
extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp